logging.level:
  root: WARN
  org.apache.pulsar.common.util.netty.DnsResolverUtil: ERROR
  com.acme: INFO
  org.springframework: INFO

spring:
  cloud:
    function:
      definition: customerSignupProcessor
    stream:
      bindings:
        customerSignupProcessor-in-0:
          destination: user-signup-topic
          consumer:
            use-native-decoding: true
        customerSignupProcessor-out-0:
          destination: customer-signup-topic
          producer:
            use-native-encoding: true
      pulsar:
        bindings:
          customerSignupProcessor-in-0:
            consumer:
              message-type: com.acme.pulsar.model.UserSignup
          customerSignupProcessor-out-0:
            producer:
              message-type: com.acme.pulsar.model.CustomerSignup
